[package]
name = "chat"
version = "0.0.0"
##workspace = "./"
edition = "2021"
publish = false

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
serde_json = "1.0"

[dev-dependencies]
rand = "0.8"
